import { createContext, useContext, useState, useEffect, useMemo } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext(null);

const translations = {
  derja: {
    name: 'Tunisian Derja',
    // Auth
    welcomeBack: 'مرحبا بيك',
    signInSubtitle: 'دخّل لحسابك في LawyerUp',
    createAccount: 'عمّل حساب',
    joinSubtitle: 'اشترك معانا في أكبر بلاصة قانونية في تونس',
    selectRole: 'شوف رولك',
    user: 'مستعمل',
    lawyer: 'محامي',
    individual: 'فرد',
    emailAddress: 'الايمايل',
    password: 'الموت دي باس',
    confirmPassword: 'أكّد الموت دي باس',
    fullName: 'الاسم الكامل',
    phoneNumber: 'نمرة التيليفون',
    signIn: 'دخّل',
    dontHaveAccount: 'ما عندكش حساب؟',
    alreadyHaveAccount: 'عندك حساب؟',
    signUp: 'سجّل',
    uploadDiploma: 'حمّل الديبلوم *',
    tapToUpload: 'انقز باش تحمّل الديبلوم',
    requiredForVerification: 'لازم للتوثيق',
    diplomaUploaded: 'تحمّل الديبلوم بالنجاح',
    remove: 'فسخ',
    lawyerVerificationNote: 'حسابات المحامين يلزمها توثيق قبل ما تنجّم',
    // Profile
    signOut: 'خرُج',
    personalInfo: 'معلوماتي',
    myCases: 'القضايا متاعي',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    help: 'مساعدة',
    userAccount: 'حساب مستعمل',
    verifiedLawyer: 'محامي موثّق',
    editProfile: 'بدّل البروفايل',
    availability: 'التوفّر',
    certifications: 'الشهايد',
    language: 'لغة',
    theme: 'الثيم',
    light: 'فاتح',
    dark: 'غامق',
    // Landing Page
    getLegalHelp: 'احصل على مساعدة قانونية',
    landingSubtitle: 'توصّل مع محامين موثوقين في تونس',
    tryAI: 'جرّب المساعد AI',
    getStarted: 'ابدا',
    typeMessage: 'اكتب مساج...',
    freePromptsLeft: 'باقي {count} من 3 أسئلة مجانية',
    loginRequired: 'لازم تدخّل',
    usedAllPrompts: 'خلّصت كل الأسئلة المجانية',
    loginToContinue: 'دخّل باش تكمّل',
    login: 'دخّل',
    // Tabs
    home: 'الدار',
    chat: 'ديسكوسيون',
    lawyers: 'المحامين',
    profile: 'البروفايل',
    cases: 'القضايا',
    users: 'المستعملين',
    logs: 'السجلات',
    // Landing Page AI
    aiWelcome: 'مرحبا بيك! أنايا مساعدك القانوني بالذكاء الاصطناعي، متخصص في القانون التونسي. جرّبني بـ 3 أسئلة مجانية!\n\nنجّم نعاونوك في:\n• القانون المدني والعائلي\n• القانون التجاري والأعمال\n• قانون العمل\n• قانون العقارات\n• القانون الجنائي\n\nشنوّة نجّم نعاونك ليوم؟',
    aiLegalAssistant: 'مساعد قانوني AI',
    freeQuestionsRemaining: 'باقي {count} سؤال مجاني',
    freeTrialUsed: 'خلّصت التجربة المجانية',
    askLegalQuestion: 'اسأل سؤال قانوني...',
    signInToContinue: 'دخّل باش تكمّل...',
    continueJourney: 'كمّل رحلتك القانونية',
    usedFreeQuestions: 'خلّصت الـ 3 أسئلة متاعك! دخّل باش تكمّل مع مساعدنا القانوني وتوصّل مع محامين تونسيين موثوقين.',
    unlimitedAI: 'استشارات قانونية AI بلا حدود',
    connectLawyers: 'توصّل مع محامين موثوقين',
    saveHistory: 'احفظ هيستوري ديسكوسيوناتك',
    createFreeAccount: 'عمّل حساب مجاني',
    // User Dashboard
    greeting: 'أهلا',
    quickActions: 'أكسيونات سريعة',
    aiAssistant: 'مساعد AI',
    findLawyer: 'لقى محامي',
    heroCardTitle: 'ديسكوتي مع مساعدنا القانوني AI',
    heroCardDesc: 'ديسكوتي مع مساعدنا AI باش تاخذ نصايح قانونية فورية على القانون التونسي.',
    recentActivity: 'آخر الأنشطة',
    browseBySpecialty: 'دوّر حسب الاختصاص',
    availableNow: 'موجودين دحوا',
    seeAll: 'شوف الكل',
    noAvailableLawyers: 'ما كاش محامين موجودين دحوا',
    // Lawyers Page
    searchLawyers: 'لقى في المحامين...',
    filterBySpec: 'فيلتري حسب الاختصاص',
    allSpecializations: 'كل الاختصاصات',
    available: 'موجود',
    unavailable: 'مش موجود',
    requestContact: 'اطلب تواصل',
    casesLabel: 'قضية',
    yrsLabel: 'سنة',
    contactLawyer: 'كلّم المحامي',
    yourMessage: 'مساجك',
    writeMessage: 'اكتب مساجك هوني...',
    sendRequest: 'ابعث الطلب',
    close: 'سكّر',
    // Lawyer Dashboard
    welcomeBackLawyer: 'مرحبا بعودتك،',
    pending: 'في الانتظار',
    active: 'نشيط',
    completed: 'خلص',
    rejected: 'مرفوض',
    thisMonth: 'هذا الشهر',
    pendingCases: 'قضايا في الانتظار',
    noPendingCases: 'مافيش قضايا في الانتظار',
    viewAllCases: 'شوف كل القضايا',
    accept: 'قبل',
    reject: 'ارفض',
    // Cases Page
    searchCases: 'لقى في القضايا...',
    filterByStatus: 'فيلتري حسب الحالة',
    all: 'الكل',
    accepted: 'مقبول',
    messageClient: 'كلّم العميل',
    markComplete: 'ماركي خلص',
    low: 'باهي',
    medium: 'موين',
    high: 'عالي',
    viewDetails: 'شوف التفاصيل',
    caseDetails: 'تفاصيل القضية',
    priority: 'الأولوية',
    status: 'الحالة',
    category: 'الكاتيغوري',
    submittedBy: 'قدمت من طرف',
    description: 'الوصف',
    // Contact Requests (lawyer side)
    requests: 'الطلبات',
    contactRequests: 'طلبات التواصل',
    noRequests: 'مافيش طلبات',
    noRequestsDesc: 'ما وصلوكش طلبات تواصل بعد',
    requestFrom: 'طلب من',
    phoneLabel: 'تيليفون',
    acceptRequest: 'قبل',
    rejectRequest: 'ارفض',
    requestAccepted: 'قبلت الطلب',
    requestRejected: 'رفضت الطلب',
    pendingRequests: 'في الانتظار',
    allRequests: 'الكل',
    // Common UI
    cancel: 'إلغاء',
    saveChanges: 'احفظ التغييرات',
    deleteLabel: 'احذف',
    submitLabel: 'أرسل',
    updateBtn: 'حدّث',
    freeLabel: 'مجاني',
    viewAll: 'شوف الكل',
    noLawyersFound: 'ما لقانا محامين',
    message: 'مساج',
    videoCall: 'كول فيديو',
    noResultsFound: 'ما لقانا نتائج',
    caseDetails: 'تفاصيل القضية',
    mAgo: 'د فات',
    rejectRequest: 'رفض الطلب',
    rejectRequestConfirm: 'واش أكيد تحب ترفض هذا الطلب؟',
    searchRequests: 'دور في الطلبات...',
    tryDifferentSearch: 'جرب كلمة أخرى',
    pendingRequestsSubtitle: (n) => `${n} طلب في الانتظار`,
    // Home
    startConversation: 'ابدا ديسكوسيون',
    noActivityYet: 'مافيش نشاط بعد',
    legalCase: 'قضية قانونية',
    caseSubmitted: 'قضية مقدمة',
    caseAccepted: 'قضية مقبولة',
    caseResolved: 'قضية محلولة',
    caseRejected: 'قضية مرفوضة',
    justNow: 'دحوا',
    hAgo: 'س فات',
    dAgo: 'ي فات',
    wAgo: 'أس فات',
    myAppointments: 'مواعيدي',
    myLegalVault: 'خزنتي القانونية',
    noUpcomingAppointments: 'مافيش مواعيد',
    noFilesYet: 'مازال ما حمّلتش ملفات',
    uploading: 'يتحمّل...',
    // Chat screen
    chatHistory: 'هيستوري الديسكوسيونات',
    newChat: 'ديسكوسيون جديد',
    chatHint: 'انقز باش تفتح · اضغط طويل باش تمسح',
    noChatsYet: 'مازال ما بداش ديسكوسيون',
    startChat: 'ابدا ديسكوسيون',
    specializedIn: 'متخصص في القانون التونسي',
    loadingChats: 'يحمّل الديسكوسيونات...',
    tapToView: 'انقز باش تشوف',
    // Inbox
    inbox: 'الرسايل',
    unread: 'غير مقروء',
    noConversationsYet: 'مازال ما بداش ديسكوسيون',
    hireToMessage: 'وظّف محامي باش تبعث رسائل',
    typingDots: 'يكتب...',
    lawyerIsTyping: 'المحامي يكتب',
    noMessagesYet: 'مازال ما كاش رسائل',
    typeAMessage: 'اكتب رسالة...',
    // Profile
    citizen: 'مواطن',
    displayMode: 'وضع العرض',
    myAccount: 'حسابي',
    legal: 'قانوني',
    settings: 'الإعدادات',
    myDocuments: 'وثائقي',
    // Filters
    filterAll: 'الكل',
    filterFamily: 'عائلي',
    filterCommercial: 'تجاري',
    filterCriminal: 'جنائي',
    filterLabor: 'شغل',
    filterProperty: 'عقارات',
    filterAdministrative: 'إداري',
    filterTax: 'ضرائب',
    filterImmigration: 'هجرة',
    messageLawyer: 'كلّم المحامي',
    startAChat: 'ابدا ديسكوسيون',
    noChatsYetTitle: 'مازال ما بداش ديسكوسيون',
    startConversationWithAI: 'ابدا ديسكوسيون مع المساعد القانوني AI',
    deleteChat: 'مسح الديسكوسيون',
    deleteChatConfirm: 'واش أكيد؟ ما ينجّمش يرجع.',
    loadingSession: 'يحمّل...',
    aiUnavailable: 'المساعد AI مش موجود. عاود الكرّة.',
    failedNewChat: 'فشل إنشاء ديسكوسيون جديد. عاود الكرّة.',
    failedDelete: 'فشل مسح الديسكوسيون.',
    failedLoadLawyers: 'فشل تحميل المحامين',
    permissionNeeded: 'لازم إذن',
    permissionCameraRoll: 'لازم إذن للوصول للصور!',
    permissionRequired: 'لازم إذن',
    grantPhotoAccess: 'عطي إذن الوصول للصور.',
    uploadFailed: 'فشل التحميل',
    couldNotLoadConversations: 'ما قدّرناش نحمّلوا الديسكوسيونات',
    // Lawyer card / profile modal
    availableForCases: 'موجود للقضايا',
    currentlyUnavailable: 'مش موجود دحوا',
    lawSuffix: '',
    aboutSection: 'على',
    casesStatLabel: 'قضايا',
    experienceLabel: 'خبرة',
    feeLabel: 'أتعاب',
    // Reviews
    editMyReview: 'بدّل تقييمي',
    writeReview: 'اكتب تقييم',
    updateYourReview: 'حدّث تقييمك',
    yourReviewTitle: 'تقييمك',
    reviewLabel: 'تقييم',
    reviewsLabel: 'تقييمات',
    reviewsSection: 'التقييمات',
    noReviewsYet: 'مافيش تقييمات. كون الأول!',
    tapToRate: 'انقز باش تعطي نقطة',
    shareExperience: 'شارك تجربتك (اختياري)...',
    ratingLabels: ['', 'بدش', 'موين', 'مليح', 'مليح بزاف', 'ممتاز'],
    describeMatter: 'وصف مشكلتك القانونية باختصار...',
    contactTitle: 'اتصل بي',
    // Profile (shared)
    changePasswordTitle: 'بدّل كلمة السر',
    personalInfoModalTitle: 'معلوماتي الشخصية',
    currentPasswordLabel: 'كلمة السر الحالية',
    newPasswordLabel: 'كلمة السر الجديدة',
    confirmNewPasswordLabel: 'أكد كلمة السر الجديدة',
    updatePasswordBtn: 'حدّث كلمة السر',
    // Lawyer dashboard
    acceptingCasesTitle: 'قبول القضايا',
    visibleToClients: 'ظاهر للعملاء',
    hiddenFromSearches: 'مخفي من البحث',
    newRequests: 'طلبات جديدة',
    scheduleLabel: 'الجدول',
    // Lawyer dashboard stats
    statIncoming: 'وارد',
    statActive: 'نشط',
    statCompleted: 'مكتمل',
    statThisMonth: 'هذا الشهر',
    // Lawyer dashboard home
    acceptCases: 'قبول القضايا',
    citizenAppointment: 'موعد مواطن',
    noUpcomingAppointments: 'مافيش مواعيد',
    // Lawyer inbox
    startAdminChat: 'ابدأ محادثة مع الإدارة',
    noConversationsYet: 'مازال ما بداش ديسكوسيون',
    awaitingClients: 'رسائلك راهي تستنى هنا. ابدأ مع الدعم أو انتظر طلبات العملاء.',
    // Lawyer profile section headers
    accountSettings: 'إعدادات الحساب',
    support: 'الدعم',
    // Cases filter pills
    caseIncoming: 'وارد',
    caseActive: 'نشط',
    caseCompleted: 'مكتمل',
    caseRejected: 'مرفوض',
    // Lawyer profile
    editProfileTitle: 'تعديل البروفايل',
    specializationLabel: 'الاختصاص',
    yearsExpLabel: 'سنوات الخبرة',
    bioLabel: 'عني',
    selectLabel: 'اختر...',
    acceptNewCases: 'قبول قضايا جديدة',
    visibleToClientsSeeking: 'ظاهر للعملاء اللي يدورو محامي',
    hiddenFromNewClients: 'مخفي عن البحث الجديد',
  },
  french: {
    name: 'Français',
    // Auth
    welcomeBack: 'Bienvenue',
    signInSubtitle: 'Connectez-vous à votre compte LawyerUp',
    createAccount: 'Créer un compte',
    joinSubtitle: 'Rejoignez la principale plateforme juridique de Tunisie',
    selectRole: 'Sélectionnez votre rôle',
    user: 'Utilisateur',
    lawyer: 'Avocat',
    individual: 'Particulier',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    fullName: 'Nom complet',
    phoneNumber: 'Numéro de téléphone',
    signIn: 'Se connecter',
    dontHaveAccount: "Vous n'avez pas de compte ?",
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    signUp: "S'inscrire",
    uploadDiploma: 'Télécharger le diplôme *',
    tapToUpload: 'Appuyez pour télécharger votre diplôme',
    requiredForVerification: 'Requis pour la vérification',
    diplomaUploaded: 'Diplôme téléchargé avec succès',
    remove: 'Supprimer',
    lawyerVerificationNote: 'Les comptes d\'avocat nécessitent une vérification avant activation.',
    // Profile
    signOut: 'Se déconnecter',
    personalInfo: 'Informations personnelles',
    myCases: 'Mes dossiers',
    notifications: 'Notifications',
    privacy: 'Confidentialité et sécurité',
    help: 'Aide et support',
    userAccount: 'Compte utilisateur',
    verifiedLawyer: 'Avocat vérifié',
    editProfile: 'Modifier le profil',
    availability: 'Disponibilité',
    certifications: 'Certifications',
    language: 'Langue',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    // Landing Page
    getLegalHelp: 'Obtenez de l\'aide juridique',
    landingSubtitle: 'Connectez-vous avec des avocats de confiance en Tunisie',
    tryAI: 'Essayez l\'assistant IA',
    getStarted: 'Commencer',
    typeMessage: 'Tapez un message...',
    freePromptsLeft: '{count} questions gratuites restantes sur 3',
    loginRequired: 'Connexion requise',
    usedAllPrompts: 'Vous avez utilisé toutes les questions gratuites',
    loginToContinue: 'Connectez-vous pour continuer',
    login: 'Se connecter',
    // Tabs
    home: 'Accueil',
    chat: 'Chat',
    lawyers: 'Avocats',
    profile: 'Profil',
    cases: 'Dossiers',
    users: 'Utilisateurs',
    logs: 'Journaux',
    // Landing Page AI
    aiWelcome: 'Bienvenue ! Je suis votre assistant juridique IA, spécialisé dans le droit tunisien. Essayez-moi avec 3 questions gratuites !\n\nJe peux vous aider avec :\n• Droit civil et familial\n• Droit commercial et des affaires\n• Droit du travail\n• Droit immobilier\n• Droit pénal\n\nComment puis-je vous aider aujourd\'hui ?',
    aiLegalAssistant: 'Assistant juridique IA',
    freeQuestionsRemaining: '{count} question{s} gratuite{s} restante{s}',
    freeTrialUsed: 'Essai gratuit utilisé',
    askLegalQuestion: 'Posez une question juridique...',
    signInToContinue: 'Connectez-vous pour continuer...',
    continueJourney: 'Continuez votre parcours juridique',
    usedFreeQuestions: 'Vous avez utilisé vos 3 questions gratuites ! Connectez-vous pour continuer à discuter avec notre assistant juridique IA et accéder aux avocats tunisiens vérifiés.',
    unlimitedAI: 'Consultations juridiques IA illimitées',
    connectLawyers: 'Connectez-vous avec des avocats vérifiés',
    saveHistory: 'Enregistrez l\'historique de vos conversations',
    createFreeAccount: 'Créer un compte gratuit',
    // User Dashboard
    greeting: 'Bonjour',
    quickActions: 'Actions rapides',
    aiAssistant: 'Assistant IA',
    findLawyer: 'Trouver un avocat',
    heroCardTitle: 'Discutez avec notre assistant juridique IA',
    heroCardDesc: 'Chattez avec notre assistant IA pour obtenir des conseils juridiques instantanés sur le droit tunisien.',
    recentActivity: 'Activité récente',
    browseBySpecialty: 'Parcourir par spécialité',
    availableNow: 'Disponibles maintenant',
    seeAll: 'Voir tout',
    noAvailableLawyers: 'Aucun avocat disponible pour le moment',
    // Lawyers Page
    searchLawyers: 'Rechercher des avocats...',
    filterBySpec: 'Filtrer par spécialité',
    allSpecializations: 'Toutes les spécialités',
    available: 'Disponible',
    unavailable: 'Indisponible',
    requestContact: 'Demander un contact',
    casesLabel: 'dossiers',
    yrsLabel: 'ans',
    contactLawyer: 'Contacter l\'avocat',
    yourMessage: 'Votre message',
    writeMessage: 'Écrivez votre message ici...',
    sendRequest: 'Envoyer la demande',
    close: 'Fermer',
    // Lawyer Dashboard
    welcomeBackLawyer: 'Bon retour,',
    pending: 'En attente',
    active: 'Actif',
    completed: 'Terminé',
    rejected: 'Refusé',
    thisMonth: 'Ce mois',
    pendingCases: 'Dossiers en attente',
    noPendingCases: 'Aucun dossier en attente',
    viewAllCases: 'Voir tous les dossiers',
    accept: 'Accepter',
    reject: 'Refuser',
    // Cases Page
    searchCases: 'Rechercher des dossiers...',
    filterByStatus: 'Filtrer par statut',
    all: 'Tous',
    accepted: 'Accepté',
    messageClient: 'Messagerie client',
    markComplete: 'Marquer comme terminé',
    low: 'Faible',
    medium: 'Moyen',
    high: 'Élevé',
    viewDetails: 'Voir les détails',
    caseDetails: 'Détails du dossier',
    priority: 'Priorité',
    status: 'Statut',
    category: 'Catégorie',
    submittedBy: 'Soumis par',
    description: 'Description',
    // Contact Requests (lawyer side)
    requests: 'Demandes',
    contactRequests: 'Demandes de contact',
    noRequests: 'Aucune demande',
    noRequestsDesc: 'Vous n\'avez pas encore reçu de demandes de contact',
    requestFrom: 'Demande de',
    phoneLabel: 'Téléphone',
    acceptRequest: 'Accepter',
    rejectRequest: 'Refuser',
    requestAccepted: 'Demande acceptée',
    requestRejected: 'Demande refusée',
    pendingRequests: 'En attente',
    allRequests: 'Toutes',
    // Common UI
    cancel: 'Annuler',
    saveChanges: 'Enregistrer',
    deleteLabel: 'Supprimer',
    submitLabel: 'Soumettre',
    updateBtn: 'Mettre à jour',
    freeLabel: 'Gratuit',
    viewAll: 'Voir tout',
    noLawyersFound: 'Aucun avocat trouvé',
    message: 'Message',
    videoCall: 'Appel vidéo',
    noResultsFound: 'Aucun résultat',
    caseDetails: 'Détails du dossier',
    mAgo: 'min',
    rejectRequest: 'Refuser la demande',
    rejectRequestConfirm: 'Voulez-vous vraiment refuser cette demande de contact ?',
    searchRequests: 'Rechercher des demandes...',
    tryDifferentSearch: 'Essayez un autre terme de recherche',
    pendingRequestsSubtitle: (n) => `${n} demande${n !== 1 ? 's' : ''} en attente`,
    // Home
    startConversation: 'Commencer la conversation',
    noActivityYet: 'Aucune activité pour le moment',
    legalCase: 'Dossier juridique',
    caseSubmitted: 'Dossier soumis',
    caseAccepted: 'Dossier accepté',
    caseResolved: 'Dossier résolu',
    caseRejected: 'Dossier refusé',
    justNow: 'à l\'instant',
    hAgo: 'h',
    dAgo: 'j',
    wAgo: 'sem',
    myAppointments: 'Mes rendez-vous',
    myLegalVault: 'Mon coffre juridique',
    noUpcomingAppointments: 'Aucun rendez-vous à venir',
    noFilesYet: 'Aucun fichier téléchargé',
    uploading: 'Téléchargement...',
    // Chat screen
    chatHistory: 'Historique des chats',
    newChat: 'Nouveau chat',
    chatHint: 'Appuyer pour ouvrir · Appui long pour supprimer',
    noChatsYet: 'Aucun chat pour le moment',
    startChat: 'Commencer un chat',
    specializedIn: 'Spécialisé en droit tunisien',
    loadingChats: 'Chargement des chats…',
    tapToView: 'Appuyer pour voir',
    // Inbox
    inbox: 'Messages',
    unread: 'non lu(s)',
    noConversationsYet: 'Aucune conversation',
    hireToMessage: 'Contactez un avocat pour commencer',
    typingDots: 'En train d\'écrire...',
    lawyerIsTyping: 'L\'avocat écrit',
    noMessagesYet: 'Aucun message pour le moment',
    typeAMessage: 'Tapez un message...',
    // Profile
    citizen: 'Citoyen',
    displayMode: 'Mode d\'affichage',
    myAccount: 'Mon compte',
    legal: 'Juridique',
    settings: 'Paramètres',
    myDocuments: 'Mes documents',
    // Filters
    filterAll: 'Tous',
    filterFamily: 'Famille',
    filterCommercial: 'Commercial',
    filterCriminal: 'Pénal',
    filterLabor: 'Travail',
    filterProperty: 'Immobilier',
    filterAdministrative: 'Administratif',
    filterTax: 'Fiscal',
    filterImmigration: 'Immigration',
    messageLawyer: 'Contacter l\'avocat',
    startAChat: 'Démarrer un chat',
    noChatsYetTitle: 'Pas encore de chats',
    startConversationWithAI: 'Démarrez une conversation avec l\'assistant IA',
    deleteChat: 'Supprimer le chat',
    deleteChatConfirm: 'Êtes-vous sûr ? Cette action est irréversible.',
    loadingSession: 'Chargement...',
    aiUnavailable: 'L\'assistant IA est temporairement indisponible. Réessayez.',
    failedNewChat: 'Impossible de créer un nouveau chat. Réessayez.',
    failedDelete: 'Impossible de supprimer le chat.',
    failedLoadLawyers: 'Impossible de charger les avocats',
    permissionNeeded: 'Permission requise',
    permissionCameraRoll: 'Permission d\'accès à la photothèque requise !',
    permissionRequired: 'Permission requise',
    grantPhotoAccess: 'Veuillez autoriser l\'accès à la photothèque.',
    uploadFailed: 'Échec du téléchargement',
    couldNotLoadConversations: 'Impossible de charger les conversations',
    // Lawyer card / profile modal
    availableForCases: 'Disponible pour des dossiers',
    currentlyUnavailable: 'Actuellement indisponible',
    lawSuffix: '',
    aboutSection: 'À propos',
    casesStatLabel: 'Dossiers',
    experienceLabel: 'Expérience',
    feeLabel: 'Honoraires',
    // Reviews
    editMyReview: 'Modifier mon avis',
    writeReview: 'Écrire un avis',
    updateYourReview: 'Mettre à jour votre avis',
    yourReviewTitle: 'Votre avis',
    reviewLabel: 'avis',
    reviewsLabel: 'avis',
    reviewsSection: 'Avis',
    noReviewsYet: "Aucun avis pour l'instant. Soyez le premier !",
    tapToRate: 'Appuyez pour noter',
    shareExperience: 'Partagez votre expérience (facultatif)...',
    ratingLabels: ['', 'Mauvais', 'Passable', 'Bien', 'Très bien', 'Excellent'],
    describeMatter: 'Décrivez brièvement votre situation juridique...',
    contactTitle: 'Contacter',
    // Profile (shared)
    changePasswordTitle: 'Changer le mot de passe',
    personalInfoModalTitle: 'Informations personnelles',
    currentPasswordLabel: 'Mot de passe actuel',
    newPasswordLabel: 'Nouveau mot de passe',
    confirmNewPasswordLabel: 'Confirmer le nouveau mot de passe',
    updatePasswordBtn: 'Mettre à jour le mot de passe',
    // Lawyer dashboard stats
    statIncoming: 'Entrant',
    statActive: 'Actif',
    statCompleted: 'Terminé',
    statThisMonth: 'Ce mois',
    // Lawyer dashboard home
    acceptCases: 'Accepter des dossiers',
    citizenAppointment: 'Rendez-vous citoyen',
    noUpcomingAppointments: 'Aucun rendez-vous à venir',
    // Lawyer inbox
    startAdminChat: 'Contacter l\'administration',
    noConversationsYet: 'Aucune conversation',
    awaitingClients: 'Vos messages apparaîtront ici. Commencez avec le support ou attendez les demandes clients.',
    // Lawyer profile section headers
    accountSettings: 'Paramètres du compte',
    support: 'Support',
    // Cases filter pills
    caseIncoming: 'Entrant',
    caseActive: 'Actif',
    caseCompleted: 'Terminé',
    caseRejected: 'Rejeté',
    // Lawyer dashboard
    acceptingCasesTitle: 'Accepter des dossiers',
    visibleToClients: 'Visible aux clients',
    hiddenFromSearches: 'Masqué des recherches',
    newRequests: 'Nouvelles demandes',
    scheduleLabel: 'Planning',
    // Lawyer profile
    editProfileTitle: 'Modifier le profil',
    specializationLabel: 'Spécialisation',
    yearsExpLabel: "Années d'expérience",
    bioLabel: 'Présentation',
    selectLabel: 'Choisir...',
    acceptNewCases: 'Accepter de nouveaux dossiers',
    visibleToClientsSeeking: 'Visible aux clients qui recherchent un avocat',
    hiddenFromNewClients: 'Masqué des nouvelles recherches',
  },
  english: {
    name: 'English',
    // Auth
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to your LawyerUp account',
    createAccount: 'Create Account',
    joinSubtitle: 'Join Tunisia\'s leading legal platform',
    selectRole: 'Select your role',
    user: 'User',
    lawyer: 'Lawyer',
    individual: 'Individual',
    emailAddress: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phoneNumber: '+216 Phone number',
    signIn: 'Sign In',
    dontHaveAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    uploadDiploma: 'Upload Diploma *',
    tapToUpload: 'Tap to upload your diploma',
    requiredForVerification: 'Required for lawyer verification',
    diplomaUploaded: 'Diploma uploaded successfully',
    remove: 'Remove',
    lawyerVerificationNote: 'Lawyer accounts require verification before activation.',
    // Profile
    signOut: 'Sign Out',
    personalInfo: 'Personal Information',
    myCases: 'My Cases',
    notifications: 'Notifications',
    privacy: 'Privacy & Security',
    help: 'Help & Support',
    userAccount: 'User Account',
    verifiedLawyer: 'Verified Lawyer',
    editProfile: 'Edit Profile',
    availability: 'Availability Schedule',
    certifications: 'Certifications',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    // Landing Page
    getLegalHelp: 'Get Legal Help Today',
    landingSubtitle: 'Connect with trusted lawyers in Tunisia',
    tryAI: 'Try AI Assistant',
    getStarted: 'Get Started',
    typeMessage: 'Type a message...',
    freePromptsLeft: '{count} of 3 free questions left',
    loginRequired: 'Login Required',
    usedAllPrompts: 'You\'ve used all free questions',
    loginToContinue: 'Sign in to continue chatting',
    login: 'Log In',
    // Tabs
    home: 'Home',
    chat: 'Chat',
    lawyers: 'Lawyers',
    profile: 'Profile',
    cases: 'Cases',
    users: 'Users',
    logs: 'Logs',
    // Landing Page AI
    aiWelcome: 'Welcome! I am your AI Legal Assistant, specialized in Tunisian law. Try me out with 3 free questions!\n\nI can help you with:\n• Civil & Family Law\n• Commercial & Business Law\n• Labor & Employment Law\n• Property & Real Estate Law\n• Criminal Law\n\nHow can I assist you today?',
    aiLegalAssistant: 'AI Legal Assistant',
    freeQuestionsRemaining: '{count} free question{s} remaining',
    freeTrialUsed: 'Free trial used',
    askLegalQuestion: 'Ask a legal question...',
    signInToContinue: 'Sign in to continue...',
    continueJourney: 'Continue Your Legal Journey',
    usedFreeQuestions: 'You\'ve used your 3 free questions! Sign in to continue chatting with our AI Legal Assistant and unlock access to verified Tunisian lawyers.',
    unlimitedAI: 'Unlimited AI legal consultations',
    connectLawyers: 'Connect with verified lawyers',
    saveHistory: 'Save your conversation history',
    createFreeAccount: 'Create Free Account',
    // User Dashboard
    greeting: 'Hello',
    quickActions: 'Quick Actions',
    aiAssistant: 'AI Assistant',
    findLawyer: 'Find Lawyer',
    heroCardTitle: 'Chat with our AI Legal Assistant',
    heroCardDesc: 'Chat with our AI assistant for instant legal insights on Tunisian law.',
    recentActivity: 'Recent Activity',
    browseBySpecialty: 'Browse by Specialty',
    availableNow: 'Available Now',
    seeAll: 'See All',
    noAvailableLawyers: 'No lawyers available right now',
    // Lawyers Page
    searchLawyers: 'Search lawyers...',
    filterBySpec: 'Filter by specialty',
    allSpecializations: 'All Specializations',
    available: 'Available',
    unavailable: 'Unavailable',
    requestContact: 'Request Contact',
    casesLabel: 'cases',
    yrsLabel: 'yrs',
    contactLawyer: 'Contact Lawyer',
    yourMessage: 'Your message',
    writeMessage: 'Write your message here...',
    sendRequest: 'Send Request',
    close: 'Close',
    // Lawyer Dashboard
    welcomeBackLawyer: 'Welcome back,',
    pending: 'Pending',
    active: 'Active',
    completed: 'Completed',
    rejected: 'Rejected',
    thisMonth: 'This Month',
    pendingCases: 'Pending Cases',
    noPendingCases: 'No pending cases',
    viewAllCases: 'View All Cases',
    accept: 'Accept',
    reject: 'Reject',
    // Lawyer dashboard stats
    statIncoming: 'Incoming',
    statActive: 'Active',
    statCompleted: 'Completed',
    statThisMonth: 'This Month',
    // Lawyer dashboard home
    acceptCases: 'Accept Cases',
    citizenAppointment: 'Citizen Appointment',
    noUpcomingAppointments: 'No upcoming appointments',
    // Lawyer inbox
    startAdminChat: 'Start Admin Chat',
    noConversationsYet: 'No conversations yet',
    awaitingClients: 'Your messages will appear here. Start chatting with support or awaiting client inquiries.',
    // Lawyer profile section headers
    accountSettings: 'Account Settings',
    support: 'Support',
    // Cases filter pills
    caseIncoming: 'Incoming',
    caseActive: 'Active',
    caseCompleted: 'Completed',
    caseRejected: 'Rejected',
    // Cases Page
    searchCases: 'Search cases...',
    filterByStatus: 'Filter by status',
    all: 'All',
    accepted: 'Accepted',
    messageClient: 'Message Client',
    markComplete: 'Mark as Complete',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    viewDetails: 'View Details',
    caseDetails: 'Case Details',
    priority: 'Priority',
    status: 'Status',
    category: 'Category',
    submittedBy: 'Submitted by',
    description: 'Description',
    // Contact Requests (lawyer side)
    requests: 'Requests',
    contactRequests: 'Contact Requests',
    noRequests: 'No requests yet',
    noRequestsDesc: 'You haven\'t received any contact requests yet',
    requestFrom: 'Request from',
    phoneLabel: 'Phone',
    acceptRequest: 'Accept',
    rejectRequest: 'Reject',
    requestAccepted: 'Request accepted',
    requestRejected: 'Request rejected',
    pendingRequests: 'Pending',
    allRequests: 'All',
    // Common UI
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    deleteLabel: 'Delete',
    submitLabel: 'Submit',
    updateBtn: 'Update',
    freeLabel: 'Free',
    viewAll: 'View All',
    noLawyersFound: 'No lawyers found',
    message: 'Message',
    videoCall: 'Video Call',
    noResultsFound: 'No results found',
    caseDetails: 'Case Details',
    mAgo: 'm ago',
    rejectRequest: 'Reject Request',
    rejectRequestConfirm: 'Are you sure you want to reject this contact request?',
    searchRequests: 'Search requests...',
    tryDifferentSearch: 'Try a different search term',
    pendingRequestsSubtitle: (n) => `${n} pending request${n !== 1 ? 's' : ''}`,
    // Home
    startConversation: 'Start Conversation',
    noActivityYet: 'No activity yet',
    legalCase: 'Legal case',
    caseSubmitted: 'Case submitted',
    caseAccepted: 'Case accepted',
    caseResolved: 'Case resolved',
    caseRejected: 'Case rejected',
    justNow: 'just now',
    hAgo: 'h ago',
    dAgo: 'd ago',
    wAgo: 'w ago',
    myAppointments: 'My Appointments',
    myLegalVault: 'My Legal Vault',
    noUpcomingAppointments: 'No upcoming appointments',
    noFilesYet: 'No files uploaded yet',
    uploading: 'Uploading...',
    // Chat screen
    chatHistory: 'Chat History',
    newChat: 'New Chat',
    chatHint: 'Tap to open · Long-press to delete',
    noChatsYet: 'No chats yet',
    startChat: 'Start a Chat',
    specializedIn: 'Specialized in Tunisian Law',
    loadingChats: 'Loading chats…',
    tapToView: 'Tap to view',
    // Inbox
    inbox: 'Messages',
    unread: 'unread',
    noConversationsYet: 'No conversations yet',
    hireToMessage: 'Hire a lawyer to start messaging',
    typingDots: 'Typing...',
    lawyerIsTyping: 'Lawyer is typing',
    noMessagesYet: 'No messages yet',
    typeAMessage: 'Type a message...',
    // Profile
    citizen: 'Citizen',
    displayMode: 'Display Mode',
    myAccount: 'My Account',
    legal: 'Legal',
    settings: 'Settings',
    myDocuments: 'My Documents',
    // Filters
    filterAll: 'All',
    filterFamily: 'Family',
    filterCommercial: 'Commercial',
    filterCriminal: 'Criminal',
    filterLabor: 'Labor',
    filterProperty: 'Property',
    filterAdministrative: 'Administrative',
    filterTax: 'Tax',
    filterImmigration: 'Immigration',
    messageLawyer: 'Message Lawyer',
    startAChat: 'Start a Chat',
    noChatsYetTitle: 'No chats yet',
    startConversationWithAI: 'Start a new conversation with your AI legal assistant',
    deleteChat: 'Delete Chat',
    deleteChatConfirm: 'Are you sure? This cannot be undone.',
    loadingSession: 'Loading...',
    aiUnavailable: 'AI assistant is temporarily unavailable. Please try again.',
    failedNewChat: 'Failed to create new chat. Please try again.',
    failedDelete: 'Failed to delete chat.',
    failedLoadLawyers: 'Failed to load lawyers',
    permissionNeeded: 'Permission needed',
    permissionCameraRoll: 'Permission to access the camera roll is required!',
    permissionRequired: 'Permission required',
    grantPhotoAccess: 'Please grant photo library access.',
    uploadFailed: 'Upload Failed',
    couldNotLoadConversations: 'Could not load conversations',
    // Lawyer card / profile modal
    availableForCases: 'Available for cases',
    currentlyUnavailable: 'Currently unavailable',
    lawSuffix: 'Law',
    aboutSection: 'About',
    casesStatLabel: 'Cases',
    experienceLabel: 'Experience',
    feeLabel: 'Fee',
    // Reviews
    editMyReview: 'Edit My Review',
    writeReview: 'Write a Review',
    updateYourReview: 'Update Your Review',
    yourReviewTitle: 'Your Review',
    reviewLabel: 'review',
    reviewsLabel: 'reviews',
    reviewsSection: 'Reviews',
    noReviewsYet: 'No reviews yet. Be the first!',
    tapToRate: 'Tap to rate',
    shareExperience: 'Share your experience (optional)...',
    ratingLabels: ['', 'Poor', 'Fair', 'Good', 'Very Good', 'Excellent'],
    describeMatter: 'Describe your legal matter briefly...',
    contactTitle: 'Contact',
    // Profile (shared)
    changePasswordTitle: 'Change Password',
    personalInfoModalTitle: 'Personal Information',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    updatePasswordBtn: 'Update Password',
    // Lawyer dashboard
    acceptingCasesTitle: 'Accepting Cases',
    visibleToClients: 'Visible to clients',
    hiddenFromSearches: 'Hidden from searches',
    newRequests: 'New Requests',
    scheduleLabel: 'Schedule',
    // Lawyer profile
    editProfileTitle: 'Edit Profile',
    specializationLabel: 'Specialization',
    yearsExpLabel: 'Years of Experience',
    bioLabel: 'Bio',
    selectLabel: 'Select...',
    acceptNewCases: 'Accept New Cases',
    visibleToClientsSeeking: 'Visible to clients seeking lawyers',
    hiddenFromNewClients: 'Hidden from new client searches',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('derja');

  useEffect(() => {
    loadLanguage();
  }, []);

  async function loadLanguage() {
    try {
      const stored = await AsyncStorage.getItem('lawyerup_language');
      if (stored) {
        setLanguage(stored);
      }
    } catch (e) {
      console.error('Failed to load language', e);
    }
  }

  async function changeLanguage(lang) {
    setLanguage(lang);
    await AsyncStorage.setItem('lawyerup_language', lang);
  }

  const value = useMemo(() => ({
    language,
    t: translations[language],
    changeLanguage,
    availableLanguages: [
      { key: 'derja', label: 'التونسية' },
      { key: 'french', label: 'Français' },
      { key: 'english', label: 'English' },
    ],
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
